import { StyleSheet, Dimensions } from 'react-native';
const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get('window');
const TextStrings = {
  logoUri:   'https://imagescdn.jaypore.com/img/app/brands/jaypore/jaypore.png',
  tagline:   "India's most beautiful products",
  closeIcon: '✕',
  getOtp: {
    welcome:          'A warm welcome to our family!',
    offerPrefix:      'Use code ',
    offerCode:        'JPNEW10',
    offerMiddle:      ' to avail an exclusive ',
    offerDiscount:    '10% OFF',
    offerSuffix:      ' on your debut purchase.',
    phonePlaceholder: 'Phone Number',
    btnLabel:         'Get OTP',
  },
  verify: {
    back:             '‹  Back',
    otpInfoPrefix:    'Please enter OTP sent to +91 ',
    otpPlaceholder:   'Enter OTP',
    remainingLabel:   'Remaining Time ',
    resendWaitPrefix: 'Resend OTP in ',
    resendLabel:      'Resend OTP',
    btnLabel:         'Verify',
    attemptsLabel:    (n) => `You have ${n}/3 attempts remaining`,
    errors: {
      expired:  'OTP expired! Please go back and try again.',
      invalid:  'Please enter valid OTP',
      wrongOtp: (n) => `Wrong OTP! You have ${n}/3 attempts remaining`,
    },
  },
  signup: {
    title:                'Create Account',
    subtitle:             'Please help us with this information for your personal account.',
    mobileLabel:          'Mobile',
    mobilePrefix:         '+91 ',
    firstNamePlaceholder: 'First Name',
    lastNamePlaceholder:  'Last Name',
    emailPlaceholder:     'Email',
    genderOptions:        ['Male', 'Female', 'Other'],
    dobPlaceholder:       ' Date of Birth',
    termsPrefix:          "I agree to Jaypore's ",
    termsOfUse:           'Terms of Use',
    termsAnd:             ' and ',
    privacyPolicy:        'Privacy Policy',
    termsSuffix:          '.',
    checkmark:            '✓',
    backBtn:              '‹  Back to Verify',
    btnLabel:             'Submit',
    errors: {
      firstName: 'Please enter your first name',
      email:     'Please enter valid email',
      terms:     'Please agree to Terms of Use',
    },
  },
};
const Colors = {
  primary:       '#BB4225',
  bgScreen:      '#FFFFFF',
  bgReadOnly:    '#F5F5F5',
  bgInput:       '#FFFFFF',
  bgBtnDisabled: '#D0D0D0',
  border:        '#E0E0E0',
  borderLight:   '#CCCCCC',
  textDark:      '#212121',
  textMuted:     '#757575',
  textWhite:     '#FFFFFF',
  overlayBg:     'rgba(0,0,0,0.5)',
};
const Font = {
  regular: 'Lato-Regular',
  bold:    'Lato-Bold',
};
export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: Colors.overlayBg,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  container: {
    backgroundColor: Colors.bgScreen,
    width: '100%',
    height: SCREEN_HEIGHT,
    paddingHorizontal: 30,
    paddingTop: 44,
    paddingBottom: 40,
  },
  closeBtn: {
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  closeText: {
    fontSize: 20,
    color: '#333333',
    fontFamily: Font.regular,
  },
  screen: {
    alignItems: 'center',
    width: '100%',
  },
  logoImage: {
    height: 32,
    width: 190,
    marginTop: 10,
    marginBottom: 6,
  },
  tagline: {
    fontSize: 12,
    color: '#9E9E9E',
    fontFamily: Font.regular,
    marginBottom: 36,
    textAlign: 'center',
  },
  welcome: {
    fontSize: 16,
    fontFamily: Font.bold,
    color: Colors.textDark,
    textAlign: 'center',
    marginBottom: 14,
  },
  offerWrap: {
    fontSize: 13,
    fontFamily: Font.regular,
    color: Colors.textDark,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 30,
    width: '100%',
  },
  offerNormal: {
    fontFamily: Font.regular,
    fontSize: 13,
    color: Colors.textDark,
  },
  offerBold: {
    fontFamily: Font.bold,
    fontSize: 13,
    color: Colors.textDark,
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: 6,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 14,
    fontFamily: Font.regular,
    marginBottom: 16,
    color: Colors.textDark,
    backgroundColor: Colors.bgInput,
  },
  inputWrapper: {
    width: '100%',
  },
  inputReadOnly: {
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
    backgroundColor: Colors.bgReadOnly,
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 10,
    color: '#9E9E9E',
    fontFamily: Font.regular,
    marginBottom: 3,
  },
  inputValue: {
    fontSize: 14,
    color: Colors.textDark,
    fontFamily: Font.regular,
  },
  inputHalfLeft: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 14,
    fontFamily: Font.regular,
    marginBottom: 14,
    marginRight: 8,
    color: Colors.textDark,
    backgroundColor: Colors.bgInput,
  },
  inputHalfRight: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    borderRadius: 6,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 14,
    fontFamily: Font.regular,
    marginBottom: 14,
    color: Colors.textDark,
    backgroundColor: Colors.bgInput,
  },
  btn: {
    backgroundColor: Colors.primary,
    width: '100%',
    paddingVertical: 16,
    borderRadius: 6,
    alignItems: 'center',
    marginTop: 4,
  },
  btnPressed: {
    backgroundColor: '#9E3019',
    width: '100%',
    paddingVertical: 16,
    borderRadius: 6,
    alignItems: 'center',
    marginTop: 4,
  },
  btnDisabled: {
    backgroundColor: Colors.bgBtnDisabled,
    width: '100%',
    paddingVertical: 16,
    borderRadius: 6,
    alignItems: 'center',
    marginTop: 4,
  },
  btnText: {
    color: Colors.textWhite,
    fontFamily: Font.bold,
    fontSize: 15,
    letterSpacing: 0.5,
  },
  backBtn: {
    alignSelf: 'flex-start',
    marginBottom: 16,
    marginTop: 4,
  },
  backText: {
    fontSize: 14,
    fontFamily: Font.regular,
    color: Colors.textDark,
  },
  otpInfo: {
    fontSize: 13,
    fontFamily: Font.regular,
    color: Colors.textDark,
    marginBottom: 14,
    alignSelf: 'flex-start',
  },
  remainingTime: {
    alignSelf: 'flex-end',
    fontSize: 12,
    color: '#9E9E9E',
    fontFamily: Font.regular,
    marginTop: -10,
    marginBottom: 14,
  },
  resendRow: {
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  resendWait: {
    fontSize: 13,
    fontFamily: Font.regular,
    color: '#9E9E9E',
  },
  resendActive: {
    fontSize: 13,
    fontFamily: Font.regular,
    color: Colors.primary,
    textDecorationLine: 'underline',
  },
  attemptsText: {
    fontSize: 13,
    fontFamily: Font.bold,
    color: '#D4880A',
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  errorText: {
    fontSize: 12,
    color: Colors.primary,
    fontFamily: Font.regular,
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  signupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 4,
  },
  signupTitle: {
    fontSize: 18,
    fontFamily: Font.bold,
    color: Colors.textDark,
  },
  signupSubtitle: {
    fontSize: 13,
    fontFamily: Font.regular,
    color: '#9E9E9E',
    marginBottom: 18,
    lineHeight: 20,
  },
  row: {
    flexDirection: 'row',
    width: '100%',
  },
  genderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    gap: 20,
    alignSelf: 'flex-start',
  },
  genderOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: '#BBBBBB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioOuterSelected: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.primary,
  },
  genderText: {
    fontSize: 13,
    fontFamily: Font.regular,
    color: Colors.textDark,
  },
  termsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 18,
    gap: 10,
    width: '100%',
  },
  checkbox: {
    width: 16,
    height: 16,
    borderWidth: 1.5,
    borderColor: '#CCCCCC',
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
    backgroundColor: Colors.bgInput,
  },
  checkboxChecked: {
    width: 16,
    height: 16,
    borderWidth: 1.5,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  checkmark: {
    color: Colors.textWhite,
    fontSize: 10,
  },
  termsText: {
    flex: 1,
    fontSize: 13,
    fontFamily: Font.regular,
    color: Colors.textDark,
    lineHeight: 20,
  },
  termsLink: {
    textDecorationLine: 'underline',
    fontFamily: Font.bold,
    fontSize: 13,
    color: Colors.textDark,
  },
  termsNormal: {
    fontFamily: Font.regular,
    fontSize: 13,
    color: Colors.textDark,
  },
});
export default TextStrings;