export const searchData = [
  'Mensential Kalghi',
  'Mensential Necklace',
  'Mensential Brooch',
  'Mensential Cuffs & Bracelet',
  'Mensential Kalghi in Men',
  'Mensential Necklace in Men',
  'Mensential Brooch in Men',
  'Mensential Cuffs & Bracelet in Men',
  'Mensential',
  'Jaypore Shoes',
  'Shoes for Men',
  'Jaypore Shoes in Men',
  'Shoes',
  'Shoes for Women',
  'Jaypore Shoes in Women',
  'Men Black Solid Shoes',
  'Paiposh Shoes',
  'Oceedee Shoes',
  'Colaba Causeway Shoes',
];
